---
- name: creation de FS 
  hosts: all
  become: yes
  tasks:
    - name: creer une partition
      filesystem:
        fstype: ext4
        dev: /dev/mapper/ubuntu--vg-ubuntu--lv
        force: yes
    - name: monter le FS 
      mount:
        path: /applis
        src: /dev/mapper/ubuntu--vg-ubuntu--lv
        fstype: ext4
        state: present
        opts: defaults