---
- name: creation de FS 
  hosts: all
  become: yes
  tasks:

    - name: creation de partition
      parted: 
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present 
    
    - name: creation de VG
      lvg:
        vg: vg_apps
        pvs: /dev/sdb1
    - name: resize volume
      lvol: 
        vg: vg_apps
        lv: lv_apps
        size: 100%VG
    - name: crate filesystem
      filesystem:
        fstype: ext4
        dev: "/dev/vg_apps/lv_apps"
        force: no
    - name: create directory
      file:
        path: "/applis"
        state: directory
        mode: '0755'
    - name: montage du fs 
      mount:
        path: "/applis"
        src: "/dev/vg_apps-lv_apps"
        fstype: ext4
        opts: rw, nosuid,noexec
        state: mounted
    - name: lvm debbug
      debug: 
        msg: "{{ ansible_lvm }}"
        
    
    
