---
- name: creation de FS 
  hosts: all
  become: yes
  tasks:
    - name: creer une partition
      filesystem:
        fstype: ext4
        dev: /dev/sdb
        size: 10G
        force: yes
    - name: monter le FS 
      mount:
        path: /applis
        src: /dev/sdb
        fstype: ext4
        state: present
        opts: defaults